-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 15:28:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BiliBili_db
-- -----------------------------------------------------
-- 仿bilibili网站数据库
DROP SCHEMA IF EXISTS `BiliBili_db` ;

-- -----------------------------------------------------
-- Schema BiliBili_db
--
-- 仿bilibili网站数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BiliBili_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `BiliBili_db` ;

-- -----------------------------------------------------
-- Table `BiliBili_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BiliBili_db`.`User` ;

CREATE TABLE IF NOT EXISTS `BiliBili_db`.`User` (
  `UID` INT(9) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户唯一ID',
  `NickName` VARCHAR(16) NOT NULL COMMENT '用户昵称',
  `UserName` VARCHAR(45) NOT NULL COMMENT '用户名（唯一）',
  `Birthday` DATE NULL COMMENT '用户生日',
  `Level` INT NOT NULL COMMENT '用户等级',
  `Exp` BIGINT NOT NULL COMMENT '用户现有经验',
  `CoinsNum` DOUBLE NOT NULL COMMENT '用户现有硬币数量',
  `BCoinsNum` INT NOT NULL COMMENT '用户现有B币数量',
  `BoundEmail` VARCHAR(50) NOT NULL COMMENT '被绑定邮箱',
  `BoundPhone` VARCHAR(11) NOT NULL COMMENT '被绑定手机号',
  `BoundQQ` VARCHAR(15) NULL COMMENT '被绑定qq',
  `ConcernsNum` INT NOT NULL COMMENT '关注up主总数量',
  `FansNum` INT NOT NULL COMMENT '粉丝数量',
  `LikesNum` INT NOT NULL COMMENT '所有发布视频的总点赞数',
  `DynamicNum` INT NOT NULL COMMENT '动态数量',
  `MemberPoint` INT NOT NULL COMMENT '会员积分',
  `isBigMembers` TINYINT NOT NULL COMMENT '是否为大会员',
  `isBigMembersYear` TINYINT NOT NULL COMMENT '是否为年度大会员',
  `isTodayLogin` TINYINT NOT NULL COMMENT '今日是否已登录',
  `isTodayPlay` TINYINT NOT NULL COMMENT '今日是否已播放视频',
  `todayCoinNum` INT NOT NULL COMMENT '今日投币数量（前五个币每个币+10Exp）',
  `PlaysNum` INT NOT NULL COMMENT '所有发布视频的总播放数',
  `ReadsNum` INT NOT NULL COMMENT '所有发布专栏的总阅读数',
  `BigMembersLastDay` DATE NULL COMMENT '上次开通大会员日期',
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `UID_UNIQUE` (`UID` ASC) VISIBLE,
  UNIQUE INDEX `BoundPhone_UNIQUE` (`BoundPhone` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `BiliBili_db`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BiliBili_db`.`Tag` ;

CREATE TABLE IF NOT EXISTS `BiliBili_db`.`Tag` (
  `TagID` INT NOT NULL AUTO_INCREMENT COMMENT '标签唯一ID',
  `TagName` VARCHAR(50) NOT NULL COMMENT '标签名称',
  PRIMARY KEY (`TagID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BiliBili_db`.`TreePaths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BiliBili_db`.`TreePaths` ;

CREATE TABLE IF NOT EXISTS `BiliBili_db`.`TreePaths` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，无意义',
  `Ancestor` INT NOT NULL COMMENT '祖先id',
  `Descendant` INT NOT NULL COMMENT '后代id',
  `Dept` INT NOT NULL COMMENT '深度',
  PRIMARY KEY (`Id`),
  INDEX `fk_TreePaths_Tag_idx` (`Ancestor` ASC) VISIBLE,
  INDEX `fk_TreePaths_Tag1_idx` (`Descendant` ASC) VISIBLE,
  CONSTRAINT `fk_TreePaths_Tag`
    FOREIGN KEY (`Ancestor`)
    REFERENCES `BiliBili_db`.`Tag` (`TagID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TreePaths_Tag1`
    FOREIGN KEY (`Descendant`)
    REFERENCES `BiliBili_db`.`Tag` (`TagID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
